project_id = "xxojpfhnkxpbznbmhmua"

[functions.setup-users]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.evolution-instance]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.setup-webhooks]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.sync-profile-pictures]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.test-agent-messages]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false

[functions.import-chats]
verify_jwt = false

[functions.fix-contact-names]
verify_jwt = false
